# Generated by Django 5.0.2 on 2025-07-17 10:57

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tier", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Backlink_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(max_length=500, verbose_name="Website URL"),
                ),
                (
                    "keyword_1",
                    models.CharField(max_length=255, verbose_name="Keyword 1"),
                ),
                (
                    "keyword_2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 2"
                    ),
                ),
                (
                    "keyword_3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 3"
                    ),
                ),
                (
                    "keyword_4",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 4"
                    ),
                ),
                (
                    "keyword_5",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 5"
                    ),
                ),
                (
                    "keyword_6",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 6"
                    ),
                ),
                (
                    "keyword_7",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 7"
                    ),
                ),
                (
                    "keyword_8",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 8"
                    ),
                ),
                (
                    "keyword_9",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 9"
                    ),
                ),
                (
                    "keyword_10",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 10"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="YouTube Video URL",
                    ),
                ),
                (
                    "article_document",
                    models.FileField(
                        blank=True,
                        help_text="Only .doc or .docx files allowed",
                        null=True,
                        upload_to="articles/",
                        verbose_name="Upload Article Document",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.package"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        null=True,
                    ),
                ),
                ("total_amount", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("backlink_cart", models.ManyToManyField(to="main.backlink_cart")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
