# Generated by Django 5.0.2 on 2025-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.CharField(null=True),
        ),
    ]
