# Generated by Django 5.0.2 on 2025-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_customerquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="days_to_complete",
            field=models.PositiveIntegerField(
                default=4, help_text="Estimated number of days to complete this package"
            ),
            preserve_default=False,
        ),
    ]
