# Generated by Django 5.0.2 on 2025-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_package_days_to_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="report_file",
            field=models.FileField(blank=True, null=True, upload_to="order_reports/"),
        ),
        migrations.AddField(
            model_name="orders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                null=True,
            ),
        ),
    ]
