# Generated by Django 5.0.2 on 2025-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_orders_status_orders_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="work_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                null=True,
            ),
        ),
    ]
