# Generated by Django 5.0.2 on 2025-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
