# Generated by Django 5.0.2 on 2025-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_orders_stripe_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="backlink_cart",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
