# Generated by Django 5.0.2 on 2025-07-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_backlink_cart_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Pyament_pending", "Pyament_pending"),
                    ("onprogress", "onprogress"),
                    ("Delivered", "Delivered"),
                ],
                default="Pyament_pending",
                null=True,
            ),
        ),
    ]
