# Generated by Django 5.0.2 on 2025-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_orders_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Payment_pending", "Payment_pending"),
                    ("onprogress", "onprogress"),
                    ("Delivered", "Delivered"),
                ],
                default="Payment_pending",
                null=True,
            ),
        ),
    ]
