# Generated by Django 5.0.2 on 2025-08-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempBacklinkCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255)),
                (
                    "website_url",
                    models.URLField(max_length=500, verbose_name="Website URL"),
                ),
                (
                    "keyword_1",
                    models.CharField(max_length=255, verbose_name="Keyword 1"),
                ),
                (
                    "keyword_2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 2"
                    ),
                ),
                (
                    "keyword_3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 3"
                    ),
                ),
                (
                    "keyword_4",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 4"
                    ),
                ),
                (
                    "keyword_5",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 5"
                    ),
                ),
                (
                    "keyword_6",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 6"
                    ),
                ),
                (
                    "keyword_7",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 7"
                    ),
                ),
                (
                    "keyword_8",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 8"
                    ),
                ),
                (
                    "keyword_9",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 9"
                    ),
                ),
                (
                    "keyword_10",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keyword 10"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="YouTube Video URL",
                    ),
                ),
                (
                    "article_document",
                    models.FileField(
                        blank=True,
                        help_text="Only .doc or .docx files allowed",
                        null=True,
                        upload_to="temp_articles/",
                        verbose_name="Upload Article Document",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "package_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.package"
                    ),
                ),
            ],
        ),
    ]
